language: vim
env:
  - TEST=package
  - TEST=latest

before_script: |
  if [ "$TEST" = "package" ]; then
    sudo apt-get -y update
    sudo apt-get -y install vim
  else
    cd ..
    git clone --depth 1 https://github.com/vim/vim
    cd vim
    ./configure --with-features=huge
    make
    sudo make install
    export PATH="/usr/local/bin:$PATH"
    cd "$TRAVIS_BUILD_DIR"
  fi
script: |
  make test
